!***********************************************************************!
!***********************************************************************!
!***       SELF EVOLVING ATOMISTIC KINETIC MONTE CARLO CODE          ***!
!***                        AUTHOR:XU,HAIXUAN                        ***!
!***             MATERIALS SCIENCE AND TECHNOLOGY DIVISION           ***!
!***                      OAK RIDGE NATIONAL LAB                     ***!
!***                          XUH1@ORNL.GOV                          ***!
!***                           VERSION 2.0                           ***!
!***                       ALL RIGHTS RESERVED                       ***!
!***********************************************************************!
!***********************************************************************!
!!SYSTEM VARIABLES:GLOBAL VARIABLES

MODULE SYSTEM

  IMPLICIT NONE

  REAL*8, PARAMETER :: KB = 8.617332D-5

!MPI VARIBALES
!IERR:ERROR TAG FOR MPI
!RANK:PROCESSES ID
!NPROCS:TOTAL NUMBER OF PROCESSES
  INTEGER IERR, RANK, NPROCS

!DIMER_COMM: COMMUNICATOR FOR DIMER LAMMPS
  INTEGER DIMER_COMM

!!DIMER SEARCH VARIABLES USED IN SPS LOOPS
!!DIMERPR:DIMER SEARCHES PER RANK
!!UDIMERI:UPPER DIMER INDEX
!!LDIMERI: LOWER DIMER INDEX
  INTEGER DIMERPR, UDIMERI, LDIMERI

!!NATOMC:NUMBER OF ATOMS IN THE CURRENT SYSTEM
!!NATOMR:NUMBER OF ATOMS IN THE REFERENCE LATTICE
!!NTSTEP:NUMBER OF TOTAL STEPS OF SEAKMC
!!DPAC  :WEIGHTING COUNT FOR AVERAGE DPA PER CASCADE
!!NFREKL:NUMBER OF FRENKEL PAIRS CREATED DURING ELECTRON RAD.

  INTEGER NATOMC, NATOMR, NTSTEP, DPAC, NFREKL

!!NDIMER:NUMBER OF DIMER IMAGE(HOW MANY SPS FOR EACH AV)
!!NDSMAX:MAXIMUM NUMBER OF DIMER STEPS
!!NDRMAX:MAXIMUM NUMBER OF ROTATION IN EACH DIMER STEP
!!NDEMAX:MAXIMUM NUMBER OF DEFECT IN THE SYSTEM
!!NAVMAX:MAXIMUM NUMBER OF ATOMS IN AN AV

  INTEGER NDIMER, NIRMAX, NDSMAX, NDRMAX, NDEMAX, NAVMAX

!!REST: USING RESTART FILE
!!TJOB: TYPE OF JOB
!!TDAM: TYPE OF DAMAGE
!!TOPT: TYPE OF OPTIMIZATION METHOD
!!TPBC: TYPE OF BOUNDARY CONDITIONS
!!TCRY: TYPE OF CRYSTALLINITY
!!ISTEP: CURRENT STEP OF SEAKMC
!!BSTEP: BEGINNING STEP OF SIMULATION
!!NFREQ: FREQUENCY OF OVITO OUTPUT

  INTEGER REST, TJOB, TDAM, TOPT, TPBC, TCRY, TLAT, ISTEP, BSTEP, NFREQ

!!TIME:SIMULATION TIME
!!TEMP:TEMPERATURE
!!TIME_LAST: TIME OF LAST DEFECT INTRODUCTION
!!DTIME: PRECALCULATED TIME FOR NEXT DEFECT INTRODUCTION

  REAL*8 TIME, TEMP, TIME_LAST, DTIME

!!RBOX:SIMULATION BOX SIZE IN LATTICE CONSTANTS
!!RATIO:NOT USED ANYMORE
!!RBH1:HALF OF THE BOX SIZE FOR PBC
!!RBH2:MINUS HALF OF THE BOX SIZE FOR PBC
!!EPSX:STRAIN IN X
!!EPSY:STRAIN IN Y
!!EPSZ:STRAIN IN Z
!!SIGX:STRESS IN X
!!SIGY:STRESS IN Y
!!SIGZ:STRESS IN Z

  REAL*8 RBOX, RLAT, RATIO, RBH1, RBH2, EPSX, EPSY, EPSZ, SIGX, SIGY, SIGZ

!!PRESS:SYSTEM PRESSURE TENSOR

  REAL*8, DIMENSION(6) :: PRESS

!!PCUTR:POTENTIAL CUTOFF FOR THE PAIR TERM
!!PCUTS:PCUTR*PCUTR
!!DCUTR:POTENTIAL CUTOFF FOR THE DENSITY TERM
!!DCUTS:DCUTR*DCUTR
!!DECUT:CRITERIA CUTOFF FOR IDENTIFYING THE DEFECT

  REAL*8 PCUTR, PCUTS, DCUTR, DCUTS, DECUT

!!FNRMAX:MAXIMUM FORCE FOR DIMER ROTATION
!!FNRMIN:MINIMUM FORCE FRO DIMER ROTATION
!!DSTEPF:THE TRIAL STEP SIZE IN DIMER TRANSLATION USING CG
!!DSTEPM:THE MAXIMUM STEP SIZE IN DIMER TRANSLATION
!!RDIMER:THE DISTANCE BETWEEN TWO DIMER IMAGE

  REAL*8 FNRMAX, FNRMIN, DSTEPF, DSTEPM, RDIMER

!!RAVTMP:NOT USED ANYMORE
!!RAVVAC:NOT USED ANYMORE
!!RAVINT:NOT USED ANYMORE
!!EDIFFG:NOT USED ANYMORE
!!FDCONV:CONVERGENCE CRITERIA FOR DIMER TO STOP,BASED ON FORCE

  REAL*8 RAVTMP, RAVVAC, RAVINT, EDIFFG, FDCONV

!!ENERGY:SYSTEM ENERGY
!!ENINIT:INITIAL ENERGY OF THE SYSTEM BEFORE SPS
!!ENCALC:CURRENT ENERGY OF THE SYSTEM
!!ENFINI:FINAL ENERGY OF THE SYSTEM,NOT USED VERY OFTEN
!!EMSKIP: MAXIMUM ACCEPTABLE ENERGY BARRIER FOR DIMER

  REAL*8 ENERGY, ENINIT, ENCALC, ENFINI, EMSKIP

!!DRATE:IRRADIATION DOSE RATE
!!PKAE :ENERGY OF CHOSEN PKA
!!DPA  :CURRENT DPA FOR SYSTEM
!!AVDPA:AVERAGE DPA CAUSED PER CASCADE

  REAL*8 DRATE, PKAE, DPA, AVDPA

!!ND:NUMBER OF ATOMS IN THE AV
!!NDBUFF:RECV BUFFER
!!ON:OLD ND,FOR SP RECYCLING

  INTEGER, ALLOCATABLE, DIMENSION(:) :: ND, NDBUFF, ON

!!RA:CURRENT ATOMS POSTION
!!RR:POSTION OF THE ATOMS IN THE REFERENCE LATTICE
!!EE:ENERGY OF EACH ATOM IN THE SYSTEM
!!FF:FORCE OF EACH ATOM IN THE SYSTEM

  REAL*8, ALLOCATABLE :: RA(:, :), RR(:, :), EE(:, :), FF(:, :)

!!SR:THE POSITION OF SADDLE POINT CONFIGURATION
!!SRBUFF:RECV BUFF
!!OR:OLD SR,FOR SP RECYCLING

  REAL*8, ALLOCATABLE :: SR(:, :, :), OR(:, :, :), SRBUFF(:, :, :)

!!EMIG: PRE-SELECTION ENERGIES
!!EMIC: COUNTS FOR WEIGHTING AVERAGES
!!SKIP: FOR UNFAVORABLE TRANSITION ENERGIES REDO DFSEL
!!CALC: CALCULATE THE DPA RIGHT AFTER A DAMAGE EVENT
!!SIGRELON: TURN ON STRESS RELAXATION FOR INPUT CRYSTAL

  REAL*8, ALLOCATABLE :: EMIG(:, :)
  INTEGER, ALLOCATABLE :: EMIC(:, :)
  LOGICAL :: SKIP, CALC, SIGRELON

!!TLAT_CHAR: CHAR REPRESENTATION OF TLAT (LATTICE TYPE)

  CHARACTER(LEN=5) :: TLAT_CHAR

END MODULE SYSTEM
!***********************************************************************!
!!VARIABLE ASSOCIATED WITH DEFECTS

MODULE DEFECT

  USE BINS

  IMPLICIT NONE

!!RFGRID:GRID FOR REFERENCE LATTICE

  TYPE(BINGRID) :: RFGRID

!!NDINT:NUMBER OF DEFECT AS INTERSTITIAL TYPE
!!NDVAC:NUMBER OF DEFECT AS VACANCY TYPE
!!NDTOT:NUMBER OF DEFECT IN TOTAL=NDINT+NDVAC IN MOST CASES
!!ONDTOT:OLD NUMBER OF DEFECT IN TOTAL, FOR SP RECYCLING
!!NDSTOT: NUMBER OF TOTAL DISPLACEMENTS / FRENKEL PAIRS
!!ONDSTOT: OLD NUMBER OF TOTAL DISPLACEMENTS
!!NNEIGH: NUMBER OF NEIGHBORS PER ATOM

  INTEGER NDINT, NDVAC, NDTOT, ONDTOT, NDSTOT, ONDSTOT, NNEIGH

!!TI:TAG FOR INTERSTITIAL
!!TIBUFF:TAG FOR INTERSTITIAL
!!TV:TAG FOR VACANCY
!!TVBUFF:TAG FOR VACANCY
!!II:INDEX OF INTERSTITIAL
!!IV:INDEX OF VACANCY
!!OC:SITE DWELLERS LIST
!!OCC: COUNT OF DWELLERS AT SITE

  INTEGER, ALLOCATABLE :: TI(:), TV(:), TIBUFF(:), TVBUFF(:), II(:, :), IV(:, :), OC(:, :), OCC(:)

!!RNEIGH: REFERENCE NEIGHBORS FOR REAL ATOMS

  INTEGER, ALLOCATABLE :: RNEIGH(:, :)

!!PI:POSITION OF INTERSTITIAL
!!PV:POSITION OF VACANCY
!!PX:POSTION OF DEFECTS, INCLUDING BOTH INTERSTITIAL AND VACANCY
!!OX:OLD POSITION OF DEFECTS,FOR SP RECYCLYING

  REAL*8, ALLOCATABLE :: PI(:, :), PV(:, :), PX(:, :), OX(:)

!!UPNEIGH: UPDATE NEIGHBOR LIST

  LOGICAL :: UPNEIGH

END MODULE DEFECT
!***********************************************************************!
!!KINETIC MONTE CARLO VARIABLES

MODULE KMCVAR

  IMPLICIT NONE

!!EID:EVENT ID

  INTEGER EID

!!FQSUM:FREQUENCY SUM
!!POSUM:PROBABILITY SUM

  REAL*8 FQSUM, POSUM, TMEAN

!!FQ:FREQUENCY
!!EM:MIGRATION ENERGY
!!EMBUFF:RECV BUFF
!!OE:OLD MIGRATION ENERGY,FOR SP RECYCLING

  REAL*8, ALLOCATABLE, DIMENSION(:) :: FQ, EM, EMBUFF, OE

END MODULE KMCVAR
!***********************************************************************!

!***********************************************************************!
!***********************************************************************!
!***       SELF EVOLVING ATOMISTIC KINETIC MONTE CARLO CODE          ***!
!***                        AUTHOR:XU,HAIXUAN                        ***!
!***             MATERIALS SCIENCE AND TECHNOLOGY DIVISION           ***!
!***                      OAK RIDGE NATIONAL LAB                     ***!
!***                          XUH1@ORNL.GOV                          ***!
!***                           VERSION 2.0                           ***!
!***                       ALL RIGHTS RESERVED                       ***!
!***********************************************************************!
!***********************************************************************!
